name: fstudio
description: Flutter framework for any platform.
version: 1.0.8
homepage: https://github.com/andypangaribuan/fstudio

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0
  intl: ^0.19.0
  clock: ^1.1.1
  pointycastle: ^3.6.2

dev_dependencies:
  flutter_lints: ^2.0.1
